/**
 * Tenant data transformer for converting between frontend and backend models
 */

import { BaseTransformer, FIELD_MAPPINGS } from "./base-transformer";

// Frontend Tenant model (from lib/data.ts)
export interface Tenant {
  id: string;
  name: string;
  phone: string;
  email: string;
  pg_id: string;
  room_id: string;
  bed_no: number;
  check_in: string;
  check_out: string | null;
  rent_due: string;
  rent_paid: number;
  status: string;
  created_at: string;
  updated_at: string;
}

// Backend Tenant model (expected from API)
export interface BackendTenant {
  id: string;
  name: string;
  phone: string;
  email: string;
  propertyId: string;
  roomId: string;
  bed_no: number;
  check_in: Date | any; // Firebase Timestamp or Date
  check_out: Date | any | null; // Firebase Timestamp or Date
  rent_due: Date | any; // Firebase Timestamp or Date
  rent_paid: number;
  status: string;
  tenantCode?: string; // Generated by backend
  ownerId: string;
  created_at: Date | any; // Firebase Timestamp or Date
  updated_at: Date | any; // Firebase Timestamp or Date
}

// Create Tenant data (for POST requests)
export interface CreateTenantData {
  name: string;
  phone: string;
  email: string;
  address: string;
  emergency_contact: string;
  emergency_contact_name: string;
  id_proof_type: string;
  id_proof_number: string;
  dob: string; // ISO string
  propertyId: string;
  propertyName: string; // Add propertyName field
  roomId: string;
  bed_no: number;
  check_in: string; // ISO string
  rent_due: string; // ISO string
  rent_paid: number;
  status?: string;
}

// Update Tenant data (for PUT requests)
export interface UpdateTenantData extends Partial<CreateTenantData> {
  check_out?: string | null; // ISO string
}

export class TenantTransformer extends BaseTransformer<Tenant, BackendTenant> {
  /**
   * Transform frontend Tenant to backend Tenant
   */
  toBackend(tenant: Tenant): BackendTenant {
    // Validate required fields
    this.validateRequiredFields(tenant, [
      "name",
      "phone",
      "email",
      "pg_id",
      "room_id",
      "bed_no",
      "check_in",
      "rent_due",
    ]);

    const backendTenant: BackendTenant = {
      id: tenant.id,
      name: tenant.name,
      phone: tenant.phone,
      email: tenant.email,
      propertyId: tenant.pg_id,
      roomId: tenant.room_id,
      bed_no: tenant.bed_no,
      check_in: this.isoToDate(tenant.check_in),
      check_out: tenant.check_out ? this.isoToDate(tenant.check_out) : null,
      rent_due: this.isoToDate(tenant.rent_due),
      rent_paid: tenant.rent_paid,
      status: tenant.status,
      ownerId: "", // This will be set by the backend based on JWT token
      created_at: this.isoToDate(tenant.created_at),
      updated_at: this.isoToDate(tenant.updated_at),
    };

    return this.cleanObject(backendTenant) as BackendTenant;
  }

  /**
   * Transform backend Tenant to frontend Tenant
   */
  toFrontend(backendTenant: BackendTenant): Tenant {
    const tenant: Tenant = {
      id: backendTenant.id,
      name: backendTenant.name,
      phone: backendTenant.phone,
      email: backendTenant.email,
      pg_id: backendTenant.propertyId,
      room_id: backendTenant.roomId,
      bed_no: backendTenant.bed_no,
      check_in: this.timestampToISO(backendTenant.check_in),
      check_out: backendTenant.check_out
        ? this.timestampToISO(backendTenant.check_out)
        : null,
      rent_due: this.timestampToISO(backendTenant.rent_due),
      rent_paid: backendTenant.rent_paid,
      status: backendTenant.status,
      created_at: this.timestampToISO(backendTenant.created_at),
      updated_at: this.timestampToISO(backendTenant.updated_at),
    };

    return tenant;
  }

  /**
   * Transform create tenant data for API request
   */
  toCreateRequest(data: CreateTenantData): Omit<
    BackendTenant,
    "id" | "ownerId" | "created_at" | "updated_at" | "tenantCode"
  > & {
    propertyName: string;
    address: string;
    emergency_contact: string;
    emergency_contact_name: string;
    id_proof_type: string;
    id_proof_number: string;
    dob: Date;
  } {
    this.validateRequiredFields(data, [
      "name",
      "phone",
      "email",
      "address",
      "emergency_contact",
      "emergency_contact_name",
      "id_proof_type",
      "id_proof_number",
      "dob",
      "propertyId",
      "propertyName",
      "roomId",
      "bed_no",
      "check_in",
      "rent_due",
    ]);

    return {
      name: data.name,
      phone: data.phone,
      email: data.email,
      address: data.address,
      emergency_contact: data.emergency_contact,
      emergency_contact_name: data.emergency_contact_name,
      id_proof_type: data.id_proof_type,
      id_proof_number: data.id_proof_number,
      dob: this.isoToDate(data.dob),
      propertyId: data.propertyId,
      propertyName: data.propertyName,
      roomId: data.roomId,
      bed_no: data.bed_no,
      check_in: this.isoToDate(data.check_in),
      check_out: null,
      rent_due: this.isoToDate(data.rent_due),
      rent_paid: data.rent_paid,
      status: data.status || "active",
    };
  }

  /**
   * Transform update tenant data for API request
   */
  toUpdateRequest(
    data: UpdateTenantData,
  ): Partial<
    Omit<
      BackendTenant,
      "id" | "ownerId" | "created_at" | "updated_at" | "tenantCode"
    > & { propertyName: string }
  > {
    const updateData: any = {};

    if (data.name !== undefined) updateData.name = data.name;
    if (data.phone !== undefined) updateData.phone = data.phone;
    if (data.email !== undefined) updateData.email = data.email;
    if (data.propertyId !== undefined) updateData.propertyId = data.propertyId;
    if (data.propertyName !== undefined)
      updateData.propertyName = data.propertyName;
    if (data.roomId !== undefined) updateData.roomId = data.roomId;
    if (data.bed_no !== undefined) updateData.bed_no = data.bed_no;
    if (data.check_in !== undefined)
      updateData.check_in = this.isoToDate(data.check_in);
    if (data.check_out !== undefined) {
      updateData.check_out = data.check_out
        ? this.isoToDate(data.check_out)
        : null;
    }
    if (data.rent_due !== undefined)
      updateData.rent_due = this.isoToDate(data.rent_due);
    if (data.rent_paid !== undefined) updateData.rent_paid = data.rent_paid;
    if (data.status !== undefined) updateData.status = data.status;

    return this.cleanObject(updateData);
  }

  /**
   * Transform frontend form data to create request format
   */
  fromFormDataToCreateRequest(formData: any): CreateTenantData {
    // Validate that required fields are not empty
    if (!formData.name?.trim()) throw new Error("Name is required");
    if (!formData.phone?.trim()) throw new Error("Phone is required");
    if (!formData.email?.trim()) throw new Error("Email is required");
    if (!formData.address?.trim()) throw new Error("Address is required");
    if (!formData.emergency_contact?.trim())
      throw new Error("Emergency contact is required");
    if (!formData.emergency_contact_name?.trim())
      throw new Error("Emergency contact name is required");
    if (!formData.id_proof_type?.trim())
      throw new Error("ID proof type is required");
    if (!formData.id_proof_number?.trim())
      throw new Error("ID proof number is required");
    if (!formData.dob?.trim()) throw new Error("Date of birth is required");
    if (!formData.pg_id?.trim()) throw new Error("Property is required");
    if (!formData.propertyName?.trim())
      throw new Error("Property name is required");
    if (!formData.room_id?.trim()) throw new Error("Room is required");
    if (!formData.bed_no) throw new Error("Bed number is required");
    if (!formData.check_in?.trim())
      throw new Error("Check-in date is required");
    if (!formData.rent_due?.trim())
      throw new Error("Rent due date is required");
    if (!formData.rent_paid) throw new Error("Rent amount is required");

    return {
      name: formData.name.trim(),
      phone: formData.phone.trim(),
      email: formData.email.trim(),
      address: formData.address.trim(),
      emergency_contact: formData.emergency_contact.trim(),
      emergency_contact_name: formData.emergency_contact_name.trim(),
      id_proof_type: formData.id_proof_type.trim(),
      id_proof_number: formData.id_proof_number.trim(),
      dob: new Date(formData.dob).toISOString(),
      propertyId: formData.pg_id.trim(),
      propertyName: formData.propertyName.trim(),
      roomId: formData.room_id.trim(),
      bed_no: Number(formData.bed_no),
      check_in: new Date(formData.check_in).toISOString(),
      rent_due: new Date(formData.rent_due).toISOString(),
      rent_paid: Number(formData.rent_paid),
      status: formData.status || "active",
    };
  }

  /**
   * Transform frontend form data to update request format
   */
  fromFormDataToUpdateRequest(formData: any): UpdateTenantData {
    const updateData: UpdateTenantData = {};

    if (formData.name) updateData.name = formData.name;
    if (formData.phone) updateData.phone = formData.phone;
    if (formData.email) updateData.email = formData.email;
    if (formData.pg_id) updateData.propertyId = formData.pg_id;
    if (formData.propertyName) updateData.propertyName = formData.propertyName;
    if (formData.room_id) updateData.roomId = formData.room_id;
    if (formData.bed_no) updateData.bed_no = Number(formData.bed_no);
    if (formData.check_in)
      updateData.check_in = new Date(formData.check_in).toISOString();
    if (formData.check_out)
      updateData.check_out = new Date(formData.check_out).toISOString();
    if (formData.rent_due)
      updateData.rent_due = new Date(formData.rent_due).toISOString();
    if (formData.rent_paid) updateData.rent_paid = Number(formData.rent_paid);
    if (formData.status) updateData.status = formData.status;

    return updateData;
  }
}

// Export singleton instance
export const tenantTransformer = new TenantTransformer();
